# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date creation'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_last_touch',
            field=models.DateTimeField(auto_now=True, verbose_name='date last touch'),
        ),
    ]
